objects/Test__c.object
<CustomObject>
    <fields>
        <fullName>Method__c</fullName>
        <label>Method</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Selenium</fullName>
                </value>
                <value>
                    <fullName>Automation</fullName>
                </value>
                <value>
                    <fullName>Manual</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>TestExample</label>
    <nameField>
        <label>Test Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Example</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/Example7.cls
/**
 * @File Name          : Example7.cls
 * @Description        : 
 * @Author             : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Group              : 
 * @Last Modified By   : ChangeMeIn@UserSettingsUnder.SFDoc
 * @Last Modified On   : 11/8/2019, 11:47:00 PM
 * @Modification Log   : 
 *==============================================================================
 * Ver         Date                     Author      		      Modification
 *==============================================================================
 * 1.0    11/8/2019, 11:46:34 PM   ChangeMeIn@UserSettingsUnder.SFDoc     Initial Version
**/
public with sharing class Example7 {
    public list<test__c> test;
    public void getMethod(){
        test=[Select Name,Id,Method__c from Test__c];
        System.debug('The Result' +test);
    }
}